const assert=require('node:assert/strict'),m=require('../assets/workbench06-model.js');
let s=m.initial();const go=(type,extra={})=>s=m.reduce(s,{type,text:'读取配置，修正错误，再运行检查。',...extra});
assert.equal(m.recommended(s),'send');go('send');assert.equal(JSON.parse(s.base.environment.file).timeout,30);const original=structuredClone(s.chat);go('spawn');assert.equal(s.children.a.chat.length,0);assert.equal(s.children.a.queue.length,1);go('fork');assert.deepEqual(s.children.b.chat,original);go('message');assert.equal(s.children.a.queue.length,2);assert.equal(s.children.a.chat.length,0);go('sibling');assert.match(s.notice,/UNAUTHORIZED/);assert.equal(s.children.b.queue.length,1);
const steps=[];for(let i=0;i<20;i++){const next=m.recommended(s);if(!next)break;steps.push(next);go(next);}assert.deepEqual(steps,['a','a','b','b','resume','a','a','collect']);assert.equal(s.summary,true);assert.equal(s.children.a.epoch,2);assert.equal(s.children.a.turns,2);assert.equal(s.children.b.epoch,1);assert.equal(s.children.a.resident,false);assert.ok(s.chat.some(x=>x.text.includes('结算通知')));assert.deepEqual(s.children.b.chat.slice(0,original.length),original);assert.equal(JSON.parse(s.base.environment.file).timeout,30);
const ended=structuredClone(s);go('select',{id:'missing'});assert.deepEqual(s,ended);go('resume');assert.equal(s.children.a.epoch,3);assert.equal(s.children.a.queue.length,1);go('interrupt');assert.equal(s.children.a.queue.length,1);assert.ok(m.controls(s).a);go('resume');assert.equal(s.children.a.epoch,3);assert.equal(s.children.a.queue.length,2);go('a');assert.equal(s.children.a.queue.length,0);go('interrupt');assert.equal(s.children.a.current,null);assert.equal(s.children.a.queue.length,0);go('resume');assert.equal(s.children.a.queue.length,1);go('a');go('a');assert.equal(s.children.a.resident,false);assert.equal(s.children.a.queue.length,0);
let cancelled=m.initial();for(const type of ['send','spawn','fork','message','a','interrupt','b','b','collect'])cancelled=m.reduce(cancelled,{type,text:'check'});assert.equal(cancelled.children.a.outcome,'cancelled');assert.equal(cancelled.children.a.resident,false);assert.match(cancelled.chat.at(-1).text,/不能宣告完成/);
const before=m.initial();const after=m.reduce(before,{type:'send',text:'x'});assert.equal(before.ready,false);assert.equal(after.ready,true);assert.equal(m.reduce(before,{type:'send',text:' '}).ready,false);go('reset');assert.deepEqual(s,m.initial());
let lab=m.labInitial();lab=m.labReduce(lab,'kill');assert.equal(lab.job.status,'stopping');lab=m.labReduce(lab,'done');assert.equal(lab.job.status,'cancelled');lab=m.labReduce(lab,'due');assert.equal(lab.schedule.status,'inactive');assert.equal(lab.inbox.length,1);assert.equal(lab.executed,0);lab=m.labReduce(lab,'due');assert.equal(lab.inbox.length,1);lab=m.labReduce(lab,'claim');assert.equal(lab.executed,1);lab=m.labReduce(lab,'restart');assert.equal(lab.goal.phase,'active');assert.equal(lab.goal.activation,'disarmed');assert.equal(lab.job.status,'lost');lab=m.labReduce(lab,'round');assert.equal(lab.goal.rounds,0);lab=m.labReduce(lab,'resume');lab=m.labReduce(lab,'round');lab=m.labReduce(lab,'round');lab=m.labReduce(lab,'round');assert.equal(lab.goal.phase,'blocked');assert.equal(lab.goal.rounds,2);lab=m.labReduce(lab,'resume');assert.equal(lab.goal.phase,'blocked');
console.log('Lesson 06 model: delegation/context boundaries, delayed claim, shared environment, adjacency rejection, cold resume identity, interrupt queue semantics, immutable input, Goal cap, Job stopping and Schedule receipt boundaries passed.');
