const assert=require('node:assert/strict'),m=require('../assets/workbench05-model.js');
const act=(s,type,extra={})=>m.reduce(s,{type,...extra});
let s=m.initial();assert.equal(m.recommendation(s),'send');assert.ok(m.controls(s).restore);assert.equal(m.active(s).events.length,1);
s=act(s,'send',{text:'Read fix check'});assert.equal(JSON.parse(s.environment.file).timeout,30);assert.equal(m.recommendation(s),'save');assert.ok(m.transcript(m.active(s)).some(e=>e.message.content.some(c=>c.type==='tool-call')));
const original=structuredClone(m.active(s).events),oldRequest=JSON.stringify(m.active(s).lastRequest),originalTranscript=JSON.stringify(m.transcript(m.active(s)));
s=act(s,'save');const saved=s.disk.main;s=act(s,'note');assert.ok(m.active(s).events.length>original.length);assert.equal(s.disk.main,saved);
s=act(s,'restore');assert.equal(m.active(s).events.length,original.length+1);assert.equal(m.active(s).events.at(-1).type,'session/end-seed');assert.equal(JSON.parse(s.environment.file).timeout,30);assert.deepEqual(m.active(s).events.slice(0,original.length),original);assert.equal(JSON.stringify(m.transcript(m.active(s))),originalTranscript);
const before=m.chars(m.messages(m.active(s))),prefix=structuredClone(m.active(s).events);
s=act(s,'prune');assert.ok(m.chars(m.messages(m.active(s)))<before);assert.deepEqual(m.active(s).events.slice(0,prefix.length),prefix);assert.equal(JSON.stringify(m.transcript(m.active(s))),originalTranscript);assert.equal(JSON.stringify(m.active(s).lastRequest),oldRequest);assert.equal(s.disk.main,saved);assert.ok(m.controls(s).prune,'one pass converges');
const preCompactNodes=m.surface(m.active(s)),preCompactMessages=m.messages(m.active(s));s=act(s,'compact');assert.ok(s.pending);assert.deepEqual(m.surface(m.active(s)),preCompactNodes);assert.ok(m.controls(s).send);assert.ok(m.controls(s).fork);assert.ok(m.controls(s).restore);
s=act(s,'commit');assert.equal(s.pending,null);assert.ok(m.surface(m.active(s)).length<preCompactNodes.length);assert.ok(m.chars(m.messages(m.active(s)))<m.chars(preCompactMessages));assert.equal(JSON.stringify(m.transcript(m.active(s))),originalTranscript);assert.equal(m.surface(m.active(s))[0],0);assert.equal(m.recommendation(s),'fork');
const snapshot=JSON.parse(JSON.stringify(m.active(s)));assert.deepEqual(m.messages(snapshot),m.messages(m.active(s)),'serialized log replays current view');
s=act(s,'save');const compactSaved=s.disk.main;s=act(s,'note');s=act(s,'restore');assert.deepEqual(m.messages(m.active(s)),m.messages(JSON.parse(compactSaved)));
const parentBefore=JSON.stringify(m.active(s));s=act(s,'fork');const childId=s.active;assert.equal(childId,'fork-1');assert.equal(m.active(s).inherited,JSON.parse(parentBefore).events.length);assert.equal(s.disk[childId],undefined);s=act(s,'note');assert.equal(m.recommendation(s),'parent');assert.equal(JSON.stringify(s.sessions.main),parentBefore);s=act(s,'parent');assert.equal(s.active,'main');assert.equal(m.recommendation(s),null);s=act(s,'switch',{id:childId});assert.equal(s.active,childId);assert.equal(act(s,'switch',{id:'missing'}),s);
for(const action of ['cancel','commit']){let x=act(m.initial(),'send',{text:'x'});x=act(x,'prune');const nodes=m.surface(m.active(x));x=act(x,'compact',{fail:action==='commit'});x=act(x,action);assert.equal(x.pending,null);assert.deepEqual(m.surface(m.active(x)),nodes);assert.ok(m.active(x).events.at(-1).data.error);assert.equal(m.recommendation(x),'compact');}
s=act(s,'reset');assert.deepEqual(s,m.initial());
console.log('Lesson 05: prior tool execution, save/restore tail loss, untouched environment, pruning and summary replay, preserved transcript/log prefix/request snapshots, commit/cancel/failure, fork isolation and guidance passed.');
