/* UI wiring regression using a small DOM test double; not browser visual QA. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
class Element{
 constructor(){this.children=[];this.handlers={};this.dataset={};this.attributes={};this.disabled=false;this.checked=false;this.value='';this.textContent='';this.classes=new Set();this.classList={toggle:(name,on)=>{if(on)this.classes.add(name);else this.classes.delete(name);}};}
 addEventListener(name,fn){this.handlers[name]=fn;}
 setAttribute(k,v){this.attributes[k]=v;}
 removeAttribute(k){delete this.attributes[k];}
 replaceChildren(...els){this.children=els;}
 append(...els){this.children.push(...els);}
 querySelectorAll(tag){return this.children.flatMap(c=>[...(c.tag===tag?[c]:[]),...c.querySelectorAll(tag)]);}
 click(){if(!this.disabled)this.handlers.click?.({preventDefault(){}});}
 getBoundingClientRect(){return {top:0};}
}
const html=fs.readFileSync(path.join(root,'lessons/07/index.html'),'utf8');
const nodes=Object.fromEntries([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],new Element()]));
const graphNodes=[...html.matchAll(/class="arch-node" data-node="([^"]+)" data-paths="([^"]+)"/g)].map(match=>{const e=new Element();e.dataset.node=match[1];e.dataset.paths=match[2];return e;});
const section=new Element();section.id='workbench';
const sandbox={document:{body:new Element(),getElementById:id=>nodes[id],createElement:tag=>{const e=new Element();e.tag=tag;return e;},querySelectorAll:sel=>sel==='.lesson-section'?[section]:sel==='.arch-node'?graphNodes:[],documentElement:{scrollHeight:1000}},innerHeight:600,scrollY:0,location:{},addEventListener(){},requestAnimationFrame:fn=>fn()};
sandbox.structuredClone=structuredClone;sandbox.setInterval=()=>1;sandbox.clearInterval=()=>{};sandbox.matchMedia=()=>({matches:false});sandbox.window=sandbox;vm.createContext(sandbox);
for(const file of ['lessons/07/sources.js','assets/workbench01-model.js','assets/workbench02-model.js','assets/workbench04-model.js','assets/workbench05-model.js','assets/workbench06-model.js','assets/workbench07-model.js','lessons/07/architecture.js','assets/lesson07.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox,{filename:file});
function textOf(el){return el.textContent+' '+el.children.map(textOf).join(' ');}
function recommended(id){const list=Object.entries(nodes).filter(([,e])=>e.attributes['data-recommended']==='true').map(([k])=>k);assert.deepEqual(list,id?[id]:[]);if(id)assert.equal(nodes[id].disabled,false);}
recommended('ext-next');assert.equal(nodes['desk-send'].disabled,true);assert.match(textOf(nodes['desk-chat']),/任务完成/);nodes['desk-task'].value='检查 timeout';
for(const label of ['检查运行时接口','准备审计插件','挂载 v1 组合','创建 Agent A','发送审计任务','执行本次工具','发布 v2 组合','创建 Agent B','发送审计任务','执行本次工具','移除当前定义','尝试创建新 Agent','释放 Agent A','释放 Agent B']){assert.equal(nodes['ext-next'].textContent,label);nodes['ext-next'].click();}
recommended(null);assert.equal(nodes['ext-next'].disabled,true);assert.match(textOf(nodes['ext-roster']),/已清理/);nodes['ext-agent'].value='A';nodes['ext-agent'].handlers.change();assert.match(textOf(nodes['desk-chat']),/审计通过/);nodes['ext-agent'].value='B';nodes['ext-agent'].handlers.change();assert.match(textOf(nodes['desk-chat']),/条件未通过/);nodes['ext-view'].value='result';nodes['ext-view'].handlers.change();assert.match(nodes['ext-inspection'].textContent,/"ok": false/);nodes['ext-view'].value='bindings';nodes['ext-view'].handlers.change();assert.match(nodes['ext-inspection'].textContent,/"disposed": true/);
nodes['desk-expand'].click();assert.equal(nodes['desk-expand'].attributes['aria-pressed'],'true');nodes['desk-expand'].click();nodes['view-file'].click();assert.equal(nodes['agent-desk'].attributes['data-mobile-view'],'file');nodes['view-task'].click();nodes['desk-reset'].click();recommended('ext-next');nodes['ext-next'].click();nodes['ext-next'].click();nodes['ext-failure'].checked=true;nodes['ext-next'].click();assert.match(nodes['desk-hint'].textContent,/挂载失败/);assert.equal(nodes['ext-next'].textContent,'挂载 v1 组合');nodes['ext-failure'].checked=false;nodes['ext-next'].click();nodes['ext-next'].click();nodes['ext-agent'].value='parent';nodes['ext-agent'].handlers.change();assert.equal(nodes['ext-next'].textContent,'切回待审计 Agent');nodes['ext-next'].click();nodes['desk-task'].value='';nodes['desk-send'].click();assert.match(nodes['desk-hint'].textContent,/填写/);nodes['desk-task'].value='审计';nodes['desk-send'].click();nodes['ext-mode'].value='deny';nodes['ext-next'].click();nodes['ext-view'].value='result';nodes['ext-view'].handlers.change();assert.match(nodes['ext-inspection'].textContent,/guard/);nodes['desk-send'].click();nodes['ext-mode'].value='bad-output';nodes['ext-next'].click();assert.match(nodes['ext-inspection'].textContent,/output-validation/);
assert.equal(graphNodes.length,17);graphNodes.find(n=>n.dataset.node==='tools').click();assert.match(nodes['arch-name'].textContent,/工具运行时/);assert.match(nodes['arch-source'].href,/core\/tools/);nodes['arch-node-select'].value='agent';nodes['arch-node-select'].handlers.change();assert.match(nodes['arch-detail'].textContent,/默认 AgentLoop/);nodes['arch-path'].value='runtime';nodes['arch-path'].handlers.change();assert.equal(graphNodes.find(n=>n.dataset.node==='host').classes.has('is-muted'),true);assert.equal(graphNodes.find(n=>n.dataset.node==='agent').classes.has('is-muted'),false);nodes['arch-path'].value='all';nodes['arch-path'].handlers.change();assert.ok(graphNodes.every(n=>!n.classes.has('is-muted')));const toolNode=graphNodes.find(n=>n.dataset.node==='tools');toolNode.handlers.keydown({key:'Enter',preventDefault(){}});assert.match(nodes['arch-name'].textContent,/工具运行时/);nodes['arch-expand'].click();assert.equal(nodes['arch-expand'].attributes['aria-pressed'],'true');nodes['arch-expand'].click();assert.equal(nodes['arch-expand'].attributes['aria-pressed'],'false');
console.log('Lesson 07 UI: guided controls, full conversations, failure/retry, focused/mobile panels, framework diagram nodes, keyboard selection, route highlighting and diagram expansion passed (DOM test double; not browser visual QA).');
