# -*- coding: utf-8 -*-
from pathlib import Path
import html,json,subprocess
from lab_entry import apply_entry
R=Path(__file__).resolve().parents[1];U=R.parent/'deepseek-harness';SHA='5badb15009ae1756c3afe0ae0cef1faafc290ccc'
assert subprocess.check_output(['git','-C',str(U),'rev-parse','HEAD'],text=True).strip()==SHA
D=R/'lessons/06';D.mkdir(exist_ok=True)
specs={
'spawn':('packages/subagent/subagent-spawn-in-process/src/index.ts','  start(request:',8),
'fork':('packages/subagent/subagent-fork-in-process/src/index.ts','function completedTurnPrefix',9),
'capability':('packages/subagent/subagent/src/index.ts','  async start(name:',10),
'continuation':('packages/subagent/subagent/src/continuation.ts','  async startContinuable(',14),
'message':('packages/subagent/subagent/src/continuation.ts','  async sendMessage(',16),
'resident':('packages/subagent/subagent/src/continuation-activation.ts','  private settlementState(',9),
'interrupt':('packages/subagent/subagent/src/continuation-activation.ts','      { keepInbox: true }',1),
'dispose':('packages/subagent/subagent/src/continuation-activation.ts','  private async finishDisposal(',13),
'child':('packages/subagent/subagent/src/child-agent.ts','export function resolveChildDepth(',10),
'background':('packages/subagent/tool-subagent/src/index.ts','          const runSpec = resolveDelegationRun',12),
'jobs':('packages/jobs/jobs-local/src/index.ts','  start(spec:',10),
'job-kill':('packages/jobs/jobs-local/src/index.ts','  kill(id:',3),
'parallel':('packages/workflow/workflow-ptc/src/runtime.ts','  private async parallel(',13),
'pipeline':('packages/workflow/workflow-ptc/src/runtime.ts','  private async pipeline(',13),
'workflow-host':('packages/workflow/workflow-ptc/src/host.ts','  private async drive()',16),
'goal-create':('packages/goal/goal/src/index.ts','  create(agent:',9),
'goal-resume':('packages/goal/goal/src/index.ts','  resume(agent:',15),
'goal-drive':('packages/goal/goal-round-driver/src/index.ts','    const goal = currentGoal(state)',9),
'schedule':('packages/schedule/schedule/src/runtime.ts','        // followup synchronously',13),
'goal-test':('packages/goal/goal-round-driver/tests/goal-round-driver.spec.ts',"  it('admits exact numbered",13),
'inherit-test':('packages/subagent/subagent/tests/continuation-inheritance.spec.ts',"  it('cold-resumes on",13),
'subagent-doc':('docs/subsystems/subagent.zh.md','# Subagent',1),
'workflow-doc':('packages/workflow/workflow/README.md','# @deepseek-ai',1),
'job-doc':('packages/jobs/jobs-local/README.md','# @deepseek-ai',1),
'goal-doc':('packages/goal/goal/README.md','# @deepseek-ai',1),
'schedule-doc':('docs/subsystems/schedule.zh.md','#',1),
}
sources={}
for k,(p,mark,n) in specs.items():
 lines=(U/p).read_text().splitlines();start=next(i+1 for i,l in enumerate(lines) if l.startswith(mark));sources[k]={'path':p,'start':start,'end':start+n-1,'url':f'https://github.com/deepseek-ai/deepseek-harness/blob/{SHA}/{p}#L{start}-L{start+n-1}','description':k}
excerpts=[]
def ref(k,label='源码依据'):
 return f'<a href="{sources[k]["url"]}" target="_blank" rel="noopener">{label} ↗</a>'
def code(k,title):
 s=sources[k];lines=(U/s['path']).read_text().splitlines();eid='source-'+k;excerpts.append(dict(s,id=eid));body='\n'.join(f'<span class="source-line"><span class="line-number" aria-hidden="true">{i}</span>{html.escape(lines[i-1])}</span>' for i in range(s['start'],s['end']+1));return f'<details class="source-block" id="{eid}"><summary>真实源码 · {title}</summary><p>{ref(k,s["path"])}</p><pre><code>{body}</code></pre></details>'
def p(t):return '<p>'+t+'</p>'
def note(t):return '<div class="note">'+t+'</div>'
def table(headers,rows):return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+c+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def cards(items):return '<div class="orchestration-cards">'+''.join('<article><small>'+a+'</small><h3>'+b+'</h3><p>'+c+'</p></article>' for a,b,c in items)+'</div>'
sections=[]
def section(id,title,body):sections.append((id,title,body))
section('position','把“谁来做”和“何时继续”分开',p('第五课解决同一个 Agent 如何保留经历、重建模型上下文。现在把配置修复交给父 Agent，再请检查员独立验证：检查员需要自己的会话，父 Agent 需要知道它何时完成；如果任务持续很多轮，还需要明确续跑条件；如果明天再检查，则需要时间触发。它们都让工作延续，但负责的对象不同。')+p('本课沿四条线阅读：子 Agent 管委派与会话身份；Job 管进程内后台工作的生命周期；Workflow 管一个脚本里的并行与结果聚合；Goal 和 Schedule 分别管完成目标与到时投递。Agent loop 继续负责实际轮次，Session 继续保存证据。把这些层混成一个“大任务队列”，会失去取消权、恢复边界和完成标准。')+cards([('WHO','Subagent','谁拥有独立会话？父子之间谁能发消息？'),('HOW','Workflow / Job','结果怎样收集？谁负责取消并等待清理？'),('WHEN','Goal / Schedule','现在是否继续目标？何时把提醒投进收件箱？')])+p('图中分区表示职责，没有固定串行关系。一次 Workflow 可以调用子 Agent；普通工具也能创建 Job。Goal 与 Schedule 不必相互依赖。'+ref('subagent-doc')+' · '+ref('workflow-doc')+' · '+ref('goal-doc')+' · '+ref('schedule-doc')))
section('axes','两条独立的轴：上下文与生命周期',p('Spawn / Fork 回答“从什么上下文出发”；一次性 / 可继续回答“这次结束后还能否向同一身份发消息”。因此 Fork 不等于后台运行，Spawn 也不等于只能用一次。服务按名字注册 provider，模型工具实例再选择 provider 和 backgroundMode；工具名字本身不足以判断语义。')+table(['维度','选项一','选项二'],[['上下文起点','Spawn：新会话，没有父对话种子','Fork：继承父会话已完成轮次的前缀'],['生命周期','one-shot：调用者持有 run、收取结果并 dispose','continuable：持久子会话 + 可有可无的驻留 Activation'],['返回时点','前台调用等待结果','后台可能返回 Job ID，也可能返回子会话 ID']])+p('可以类比招聘一位新同事与给同事一份已完成的工作记录；之后是只交付一次报告，还是保持一个可反复联系的项目身份，是另一项决定。类比止于身份与资料：进程内子 Agent 默认并不拥有独立操作系统或文件副本。')+p('服务先验证能力再调用 provider。请求 toolFilter、outputSchema 等能力时，不支持的 provider 会报错，不会悄悄忽略。可继续能力由 prepareContinuable 方法是否存在表示，不能拿一次性 capability flag 推断。'+ref('capability'))+code('capability','在启动之前校验能力与描述符'))
section('seed','Fork 继承到哪里，比“继承了”更重要',p('Spawn provider 将空创建规格交给共享驱动器；子 Agent 建立自己的系统提示词和用户任务，没有父对话历史。Fork provider 扫描父日志最后一个 turn/end，只复制到那个位置。当前正在调用委派工具的轮次尚未平衡，不进入种子；父会话从未完成过轮次时，Fork 也会从空历史开始。')+'''<figure class="fork-lanes"><div><b>父日志</b><span>轮次 1 已结束</span><span>轮次 2 已结束</span><span class="excluded">当前委派轮次 · 未结束</span></div><div><b>Fork 种子</b><span>轮次 1 已结束</span><span>轮次 2 已结束</span><span class="excluded">不复制</span></div><div><b>Spawn 种子</b><span class="empty">空</span><span>新的任务提示词</span></div><figcaption>绿色表示可继承的完成前缀，虚线表示排除；新子 Agent 的系统组装与后续种子处理另有步骤。</figcaption></figure>'''+p('这比第五课通用 Session fork API 更具体：通用 API 能处理选定前缀和开放尾部；这里的子 Agent provider 主动选择已完成轮次。不要把一个 provider 的选区规则说成所有 fork 的规则。')+code('fork','以最后一个 turn/end 为边界')+code('spawn','新建时不传 seed')+p('可继续 Fork 只在首次创建时捕获一次前缀。后续冷恢复重放子会话自己的历史，不重新复制父会话的新内容。给复核员的重要新要求必须放进任务或 sendMessage，不能假设它自动看见父 Agent 后续每条消息。'+ref('inherit-test','阅读继承测试')+'。本课阅读了这些测试，未执行上游测试套件。'))
section('ownership','会话长期存在，激活只是一次驻留',p('可继续子 Agent 的稳定身份是 childId。Activation（激活）是进程内一次驻留：它持有 AgentHandle 和所拥有的子激活集合，可以执行多个收件箱轮次。会话存在不代表当前占有一个运行中的 Agent；没有驻留激活也不代表记录已经删除。')+cards([('持久层','Session + descriptor','记录 provider、身份与会话经历，供发现和冷恢复。'),('进程层','Activation + Handle','保留当前 Agent、子级所有权与准入状态；结束后释放。'),('执行层','Agent Inbox + loop','这是轮次的实际队列；继续执行层不再建立另一套 FIFO。')])+p('startContinuable 先预留 childId、冻结描述符与委派配置，再由 provider 返回创建规格，在私有所有权作用域下物化 Agent。初始提示词进入收件箱后，返回 childId 与 messageId。这个返回只证明消息被接纳，不保证轮次已开始，更不保证工具已执行；在接纳之前失败则释放已经创建的资源，不把半成品身份交给调用者。'+ref('continuation'))+code('continuation','身份与描述符先建立快照')+p('自然收尾需要同时满足：Agent 没有活动工作、Inbox 为空、拥有的子激活全部释放。一个等待后代的父激活即使自身不调用模型，也不能过早释放。管理器借助 whenIdle、队列状态与观察代数重新检查条件，避免旧的空闲观察误关新的工作。')+code('resident','空队列与无子级是必要条件')+p('最终会话 flush 采用 best-effort：失败会记录警告，但不能因此永久扣住资源，后续冷恢复可能读到缺失或过期状态。强制拆卸会向下取消、按 child-first 顺序等待释放，并等待所有选中的分支收敛。会话持久记录与进程内拆卸是两回事。'+ref('dispose')))
section('communication','发消息有拓扑，也有接纳边界',p('sendMessage 要求 sender 是服务登记的那个确切在线 Agent 对象。只允许父到直接可继续子级、驻留子级到直接父级；兄弟、跨多代祖先、自身以及陈旧 Agent 对象不能凭一个已知 id 获得通信权限。消息里的 sender 来源是审计信息，不是授权凭据。')+'''<div class="adjacency"><div class="parent-node">父 Agent P</div><div class="child-pair"><span>子 A ⇄ P</span><span>子 B ⇄ P</span></div><p>A → B：拒绝；需要经 P 转发。<br>图中双向线只表示相邻关系，仍需验证在线身份与可继续模式。</p></div>'''+code('message','先验证确切在线 sender')+table(['目标状态','发送后的行为','不要误读成'],[['running','使用 steer，争取最近 step 边界领取','立刻中断工具并插入消息'],['waiting','唤醒同一个 Activation 并 steer','创建第二个并行 Agent'],['无 Activation','校验持久身份后冷恢复，再投递','重新 Fork 最新父历史']])+p('模型消息统一走 steer。人类 UI 还有内部 Queue / Steer 选择：Queue 开启后续 FIFO 轮次，Steer 尽量进入最近一步；二者最终都复用 Agent Inbox。消息已领取的事件与已接收回执是不同证据。')+p('调用方 signal 只掌管接纳之前的查找、恢复和准入。接纳之后，管理器拥有子激活；父工具随后取消，不会撤回已经接受的轮次。要停它，应走明确的 interrupt 接口。中断会请求 cancel 并 keepInbox，不等待完全停稳，不删除未领取输入，也不自动取消已经发布的后代；已经领取的输入不会重新排队。'+ref('interrupt')+' · '+ref('subagent-doc')))
section('isolation','上下文隔离不等于环境隔离',p('进程内子 Agent 会继承工作目录和谱系，读取同一工作区是正常情况。会话分离只分开了对话和运行身份；两个写作者仍可能改同一个文件。若要并行修改，必须另外决定工作区隔离、写入职责和冲突合并方式。第四课的版本观察检查可以检测一部分过期修改，却不会自动完成多方合并。')+p('resolveChildDepth 从持久谱系计算子级深度，在指定 maxDepth 时验证绝对上限。这里的上限不是“还能再生几层”，恢复父会话也不会把深度重置为根。toolFilter 则让工具在子级提示词与执行入口中同时受限；它负责可见与可调用范围，底层沙箱仍负责环境能力。')+code('child','委派深度沿父谱系递增')+p('该快照的共享 child composition 在委派时捕获沙箱策略覆盖，并把子级审批策略固定为 never；这不代表所有操作都获准，而是不会依赖一次新的交互审批。后续冷恢复沿用子日志中的快照，不随父侧后来的策略变更重捕获。教学工作台只派发只读复核任务，未模拟完整权限系统。'+ref('inherit-test')+ ' · '+ref('child','共享子级组装入口'))+note('分析：对子 Agent 的约束最好在创建与执行边界都可检查。只在任务文本里写“不要改文件”是一项模型指令，不能代替工具限制或沙箱。'))
section('jobs','后台 Job 与可继续子会话用不同的收尾方式',p('tool-subagent 根据 run_in_background 和 backgroundMode 分流。一次性前台调用等待 SubagentRun 的结果并清理；一次性后台调用让 jobs.start 持有启动、取消和 done，然后返回 jobId；可继续后台调用进入 startContinuable，返回 subagentId，不创建承载结果的 Job 包装层。')+code('background','后台模式在工具层分流')+table(['对象','返回后如何观察','结束与恢复边界'],[['one-shot 前台 run','等待最终结果','调用者 dispose；signal 贯穿启动和运行'],['one-shot 后台 Job','job_output / job_list；job_kill 请求停止','jobs-local 是进程内记录，不能跨重启续跑'],['continuable 子会话','send_message / 列表 / 结算通知','稳定会话可冷恢复，当前激活由管理器拥有']])+p('jobs-local 启动前检查服务该 owner 的控制器、参数与容量。达到并发上限会直接拒绝，生产者还没有启动；既不排队，也不抢占别人的工作。容量计算包含 running 与 stopping。调用 kill 后生产者仍可能在清理，只有 done 收敛才释放名额。')+code('jobs','启动生产者之前先验证 owner 与参数')+p('Job 输出还有保留窗口：它不是无限大的日志仓库。模型读取未读输出与用户按偏移观察输出具有不同用途；不能把一次 UI 阅读解释成模型已经消费结果。owner 或服务释放时会取消并等待相关工作，记录属于内存，进程重启后没有自动恢复协议。'+ref('job-doc')))
section('workflow','Workflow 把聚合写成程序，但不保存运行现场',p('当工作可以拆成多项独立审查，逐条让父模型发起、等待、汇总，会消耗更多模型往返。Workflow 允许模型提供一个 JavaScript 脚本，通过 agent、parallel、pipeline、phase、log 组织工作，最终返回 JSON。接口与执行引擎分离，当前 PTC engine 负责隔离执行与宿主回调。这个减少往返的收益是基于实现的分析，不是性能基准结论。')+'''<div class="pipeline-lanes"><div><b>文件 A</b><span>读取</span><span>审查</span><span>汇总</span></div><div><b>文件 B</b><span class="slow">读取较慢</span><span>审查</span><span>汇总</span></div><p>每一行内部有先后顺序，行之间没有跨阶段屏障；A 不必等 B 读完再审查。宽度只示意时间，不是测量。</p></div>'''+p('parallel 用输入顺序收集结果，并不按完成顺序打乱数组。pipeline 对每个 item 顺序执行 stage；不同 item 同时前进，没有“全部读完再全部审查”的全局屏障。并发上限、item 上限与子 Agent 数量上限是不同约束，不能仅看 Promise.all 就认为资源无限。'+ref('pipeline'))+code('parallel','普通失败为 null，fatal 继续抛出')+p('失败分为两层：普通子运行未完成时 agent() 返回 null，脚本决定跳过或替代；普通阶段异常可令该 item 变为 null 并跳过余下阶段。非法 hook 参数、不支持能力或越界等 fatal WorkflowError 不能悄悄吞成 null，否则配置错误会伪装成“没有发现问题”。')+p('启动前的元数据与脚本校验可能直接拒绝；一旦拿到 run，其 result 用 completed / error / cancelled 表达终态，不以拒绝 promise 表达脚本失败。调用者仍必须 dispose，等待脚本和子级清理。workflow 工具目前前台等待完整结果，观察事件可显示进度，但父模型不会自动收到中间子消息。'+ref('workflow-host'))+note('能力边界：当前 Workflow 没有运行日志检查点与断点续跑，没有持久化中间变量，也没有脚本内递归 workflow()。进程重启后不能从上一条 JavaScript 语句继续。不要把“编排”直接解释成持久工作流。'+ref('workflow-doc')))
section('goal','Goal 记住目标，Driver 决定下一轮',p('Goal 面向同一 Session 中跨多轮的一个完成目标。服务记录 objective、revision、phase 和 roundsStarted；自动续跑由独立 goal-round-driver 提供。只安装状态服务不会产生新的模型请求，也不会创建额外子 Agent。常规单轮问题没有必要转成 Goal。')+table(['状态层','可选值','是否随 Session 恢复'],[['持久 phase','active / paused / blocked / complete','是，来自 goal/change 投影'],['运行 activation','armed / disarmed','否，新 Agent 生命周期会 disarm'],['身份与版本','id + revision','是，更新需精确匹配'],['轮次计数','已接纳的正编号目标轮次','是，排队本身还不算已执行轮次']])+p('创建 Goal 会进入 active 并 armed；恢复 Session 或 Fork 能恢复 active 的状态，却不会继承上一个运行实例的续跑授权。此时要显式 resume。服务更新采用精确 id + revision，旧界面的操作不能覆盖新目标；resume 也会检查轮数是否还有余量。')+code('goal-resume','恢复前核对状态与轮数')+p('Driver 等待确切 Agent 空闲、没有竞争输入，并在需要时做会话检查点，再预留最多一个后续轮次。它用 followup 放入 Goal 来源消息，进入 pre-step 时再次验证目标版本、内容、轮号和授权，防止等待期间目标已暂停或修改却仍继续。用户输入有机会先执行，不被续跑无条件挤掉。')+code('goal-drive','只有 active 且 armed 才继续，并检查上限')+p('达到轮数上限会 block，原因码是 round-limit；不是自动宣告完成，也不是无限循环重试。检查点失败会取消自动续跑授权，避免在不能确认状态的情况下继续。完成判断仍需要任务证据，不能仅凭“模型回复了一段话”推定目标已达到。'+ref('goal-test','对应轮数上限测试')+'。本课核查了测试断言，但未运行上游测试。'))
section('schedule','Schedule 的回执只到收件箱',p('Schedule 为某个原 Session 保存时间规则和提示词；到时由宿主取得该 Session，把消息 followup 到收件箱。它负责时间触发，不负责完成目标、模型执行成功或外部通知渠道。会话未加载时可由宿主恢复；只是打开任务列表或修改时间不会激活 Agent。')+'''<ol class="delivery-steps"><li><b>到时</b><span>恢复原 Session，再检查实际时间</span></li><li><b>入队</b><span>followup 接纳提醒消息</span></li><li><b>持久确认</b><span>Session flush，再提交任务回执与下一目标</span></li><li><b>执行</b><span>Agent 后续领取；不属于发送回执的保证</span></li></ol>'''+p('前三格表示本课关注的投递边界；最后一格可能与宿主后续操作交错，不能理解为每次都严格等待任务记录写完才调用模型。这里强调的是回执承诺的范围。')+code('schedule','先入队并 flush，再写投递回执')+p('一次性规则确认投递后 inactive；重复规则更新下一目标。一个重复任务批次可能共享 messageId，所以回执条数也不能等同于模型请求数。时间编辑带完整 expected 记录，在同一个 FIFO 中比较后再写，若正常投递已经推进记录，旧编辑应得到 conflict。')+p('Session 存储与任务记录存储没有跨库原子事务。若消息已经持久化、任务记录尚未提交时崩溃，重试可能再次投递；有回执不等于实现了 exactly-once。投递确认失败时规则保留并告警，后续管理变更或重启可重试。删除规则停止未来投递并移除该规则回执，不撤销已入队消息。'+ref('schedule-doc'))+note('在这个快照里，委派子 Agent 所拥有的 Session 不允许新建或重新配置 Schedule，因为宿主投递无法按普通会话路径触达它。需要“明天继续”时，先明确由哪个可投递的父会话承接。'))
section('workbench','让父 Agent 带着两个检查员完成任务',p('前五课默认就绪。先运行虚拟读改查，再分别创建 Spawn 检查员和 Fork 复核员；每个子 Agent 用两步展示领取输入、读取文件、生成结论和收尾。跟随高亮即可完成一轮，再冷恢复检查员，观察稳定身份与新的激活次数。切换会话查看各自完整对话，检查器展示尚未领取的消息。')+note('教学模拟：模型为固定脚本，不理解任意任务。沿用前课虚拟文件执行；不启动真实子进程、网络或后台任务。子级只读共享虚拟文件。一次“推进”合并了若干真实运行步骤；收尾把 flush / 通知 / dispose 合并，所有数据刷新即消失。Fork 教学种子固定为最初完成的父任务，不实现任意时刻的真实事件重放。')+'''
<div class="agent-workbench focus-workbench team-workbench" id="agent-desk" data-mobile-view="task">
<header class="focus-header"><div><strong>Agent · 委派工作台</strong><small>前五课能力默认就绪 · 聚焦上下文、通信与激活</small></div><button id="desk-expand" type="button" aria-pressed="false">专注模式</button></header>
<div class="focus-options"><label for="team-session">查看会话</label><select id="team-session"><option value="parent">父 Agent</option></select><button id="desk-reset" type="button">重置实验</button><small>固定教学脚本 · 无真实多 Agent 执行</small></div>
<nav class="focus-mobile" aria-label="工作台区域"><button id="view-task" type="button" aria-pressed="true">对话</button><button id="view-file" type="button" aria-pressed="false">团队</button><button id="view-inspect" type="button" aria-pressed="false">观察与操作</button></nav>
<div class="focus-body">
<section class="focus-pane pane-task"><h3 id="team-chat-title">父 Agent 对话</h3><div id="desk-chat" class="desk-chat" role="log" aria-label="完整会话记录" aria-live="polite" tabindex="0"></div><div class="desk-composer"><label class="sr-only" for="desk-task">父 Agent 任务</label><textarea id="desk-task" rows="2" maxlength="2000">读取配置，修正错误，再运行检查。</textarea><button id="desk-send" type="button">运行父任务</button><small>固定读改查案例；后续通过推荐步骤派发复核。</small></div></section>
<section class="focus-pane pane-file"><h3>团队与驻留状态</h3><div id="team-roster" class="team-roster"></div><p id="team-env"></p><div class="note">会话 ID 稳定；激活可以释放并重建。所有成员读取同一份虚拟文件。</div></section>
<section class="focus-pane pane-inspect"><label for="team-view">检查器</label><select id="team-view"><option value="inbox">当前会话收件箱</option><option value="context">当前会话模型内容（教学）</option><option value="events">团队事件</option></select><pre id="team-inspection" class="desk-inspection" tabindex="0"></pre><label for="team-action">自由操作</label><select id="team-action"></select><button id="team-run" type="button">执行所选操作</button><p id="team-disabled"></p><a id="team-source" href="'''+sources['continuation']['url']+'''" target="_blank" rel="noopener">本步源码 ↗</a></section>
</div><footer class="focus-footer"><div><span class="pill">建议下一步</span><button id="team-next" type="button">开始</button></div><p id="desk-hint" role="status"></p></footer></div>
''')
section('lab','三种“继续”，用同一组动作看差异',p('下面是独立对照实验，与上面的委派案例不共享状态。初始有一个 active + armed 的 Goal、一个 running Job 和一条一次性 Schedule。点击“模拟重启”，比较它们各自保留了什么；点击“提醒到时”，观察入队回执和模型执行次数为何不同。按钮执行离散状态变更，不会设置真实定时器。')+'''<div class="orchestration-lab"><div class="lab-controls"><button data-lab="restart" type="button">模拟重启</button><button data-lab="resume" type="button">显式恢复 Goal</button><button data-lab="round" type="button">推进 Goal 一轮</button><button data-lab="kill" type="button">请求取消 Job</button><button data-lab="done" type="button">生产者 done</button><button data-lab="due" type="button">提醒到时并确认入队</button><button data-lab="claim" type="button">Agent 执行提醒</button><button data-lab="reset" type="button">重置对照</button></div><div class="orchestration-cards"><article><h3>Goal</h3><pre id="lab-goal"></pre></article><article><h3>Job</h3><pre id="lab-job"></pre></article><article><h3>Schedule</h3><pre id="lab-schedule"></pre></article></div><p id="lab-notice" role="status"></p></div>'''+p('实验把每一轮模型工作合并为一步；Goal 上限固定为 2。第二轮结束后，再推进一次会显示上限阻止后续调度。Schedule 只模拟成功投递，不模拟跨存储故障；重启也只是对内存状态施加恢复规则。真实源码的并发、持久化与失败边界由前文解释。'))
section('case','从需求到完成证据，沿一条完整路径复盘',table(['时刻','实际改变','父模型能据此知道什么'],[['父任务结束','配置 timeout 已由虚拟工具改为 30，检查返回 PASS','这次父任务已有执行证据'],['委派两个检查员','建立两个独立子会话并接纳任务','只知道任务已接受，不能提前汇总'],['发送补充要求','检查员收件箱增加消息','只知道消息已接收，不保证当前步骤已看到'],['子级读取与回复','各自产生工具结果与复核结论','要等通知或结果收集才能使用'],['激活收尾','通知父会话，释放子 AgentHandle','本次驻留结束，子会话仍可恢复'],['再次发送给检查员','复用 childId，建立下一次 Activation','它延续自身历史，不继承父侧最新全部上下文'],['父侧汇总','比较两份复核证据并给出结论','汇总是新的推理步骤，不是启动回执的属性']])+p('如果复核员报告错误，先定位错误属于文件内容、模型判断、工具执行还是基础设施；不要一概重启所有 Agent。若仅一个 item 普通失败，Workflow 可以继续聚合其余结果；若 provider 能力不匹配，应修复组合与请求。若人类更改任务，应先决定 steer 当前工作、排下一轮，还是中断后重新派发，不能把三者混用。')+p('在主工作台尝试“兄弟直接通信”，只会增加拒绝事件，不会污染对方收件箱。尝试中断检查员，可以比较未领取队列与已进入对话的消息：前者保留，后者不会自动重排。模型不确定性与操作系统并发在本实验中省略，但这些状态边界会实际变化。'))
section('tradeoffs','选择最小够用的编排层',table(['工程问题','优先考虑','付出的代价'],[['一个明确的独立复核','一次性子 Agent','上下文准备、结果收集、清理'],['需要反复联系同一位检查员','可继续子会话','持久身份、通信鉴权、冷恢复与驻留所有权'],['长工具运行时父 Agent 还要工作','Job','取消不等于收敛；进程内记录不能自动恢复'],['批量同构任务与结果聚合','Workflow','脚本错误和子任务失败需分层，运行现场不持久'],['一个目标跨很多轮仍未完成','Goal + Driver','授权状态、版本竞争、轮数上限'],['指定时间给原会话新输入','Schedule','时区规则、投递持久确认、重复投递窗口']])+p('直接串行调用的优点是状态少、失败归属清楚；当独立工作很少时，收益可能超过并行化。多个 Agent 的结果不会天然更正确：共享错误前提可能被重复放大，多个读写者也可能冲突。Spawn 减少上下文负担但需要明确任务；Fork 提供历史却继承已有假设，还可能扩大输入。这里是条件性的设计分析，不把这些组合宣称成未经验证的首创。')+p('dsh 值得研究的组合方式，是把“身份、上下文、执行者、结果、续跑授权、时间触发”分别放在可替换服务与清楚的所有权契约中。代价是维护者必须认识每个边界，不能靠一个统一状态词 completed 覆盖所有对象。'))
section('sources','沿创建、投递、收尾与续跑读源码',table(['顺序','入口','阅读时对照的机制'],[['1',ref('capability','SubagentRuntime.start'),'能力检查先于 provider 启动；run 的所有者是谁'],['2',ref('fork','completedTurnPrefix')+' / '+ref('spawn','Spawn provider'),'上下文种子如何决定'],['3',ref('continuation','ContinuationManager'),'哪个 await 之前捕获配置，何时返回回执'],['4',ref('message','sendMessage')+' / '+ref('resident','settlementState'),'相邻身份检查与收尾阻止条件'],['5',ref('background','tool-subagent')+' / '+ref('jobs','jobs-local'),'Job 路径与 continuable 路径分叉'],['6',ref('parallel','Workflow parallel')+' / '+ref('workflow-host','Host drive'),'普通错误与 fatal；最终清理'],['7',ref('goal-resume','Goal resume')+' / '+ref('goal-drive','Goal driver'),'持久状态与进程授权、轮次上限'],['8',ref('schedule','Schedule drive'),'入队、flush、记录提交之间的窗口']])+p('本课源码基准与前五课一致：0.2.1-alpha.1，提交 '+SHA+'，核查日期 2026-10-10。源码摘录可直接展开；链接固定到该提交。本课模型是教学实现，不能导入真实 dsh，也不能替代其集成测试。'))
section('recap','把每个“完成”放回它所属的对象',cards([('回执','消息已接收','只证明进入收件箱，不证明执行完成。'),('生命周期','激活 / Job / Run 已收尾','证明对应运行对象结算，不必然证明业务目标达成。'),('业务目标','Goal complete','需要任务证据，并由有权更新者明确记录。')])+table(['术语','在本课中的含义'],[['Activation','可继续子 Agent 的一次进程内驻留'],['Cold resume','从持久子会话恢复新的驻留实例'],['Owner','承担取消与资源释放责任的持有者'],['Steer','尽力在最近 step 领取的消息投递'],['Round','Goal Driver 发起并经过准入的后续目标轮次'],['Receipt','Schedule 保存的入队确认，不是执行报告']])+p('<a href="../05/">← 第五课：会话与上下文</a> · <a href="../../">返回七课目录</a>')+p('第七课将把这些边界用于扩展设计：选择插件、工具或策略入口，组合 Preset，并验证自定义行为。'))
nav=''.join(f'<a href="#{id}"><b>{i:02}</b> {t}</a>' for i,(id,t,_) in enumerate(sections,1));opts=''.join(f'<option value="{id}">{t}</option>' for id,t,_ in sections)
styles=''.join(f'<link rel="stylesheet" href="../../assets/{x}.css?v=lesson06-1">' for x in ['course','workbench01','lesson03','lesson04','lesson06'])
scripts='<script src="sources.js" defer></script>'+''.join(f'<script src="../../assets/{x}.js?v=lesson06-1" defer></script>' for x in ['workbench01-model','workbench02-model','workbench04-model','workbench05-model','workbench06-model','lesson06'])
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>06 · 子 Agent 与持续任务编排 — DSH 源码研读室</title><meta name="description" content="从源码理解 Spawn、Fork、可继续子 Agent、Job、Workflow、Goal 和 Schedule，通过紧凑工作台体验委派与通信。">{styles}{scripts}</head><body><a class="skip" href="#main">跳到正文</a><aside class="sidebar"><a class="brand" href="../../"><span class="brandmark">dsh</span><span>源码研读室<small>HARNESS FIELD NOTES</small></span></a><a class="back" href="../05/">← 第五课 · 会话与上下文</a><div class="nav-label">LESSON 06 / 本课目录</div><nav class="toc">{nav}</nav><div class="sidebar-foot"><progress id="reading-progress" max="100" value="0" aria-label="阅读位置"></progress><span id="reading-percent">阅读位置 0%</span><br>0.2.1-alpha.1 · 5badb15</div></aside><div class="mobile-header"><a href="../../">dsh / 源码研读室</a><select id="mobile-nav" aria-label="章节导航"><option value="">本课目录</option>{opts}</select></div><main class="main" id="main"><header class="hero"><div class="eyebrow">第六课 / 身份、所有权与继续工作的条件</div><h1>子 Agent<br>与持续任务编排</h1><p class="lead">把任务交出去之后，<br>谁来接收、谁在运行、谁负责收尾？</p><div class="meta"><span class="pill">深度课 06 / 07</span><span class="pill">0.2.1-alpha.1 · 5badb15</span><span class="pill">核查 2026-10-10</span></div></header><div class="note"><a href="#workbench">进入 Agent 委派工作台 →</a> · <a href="#lab">比较 Goal、Job 与 Schedule →</a></div>'''
page+='\n'.join(f'<section class="lesson-section" id="{id}"><div class="section-no">{i:02} / LESSON 06</div><h2>{t}</h2>{body}</section>' for i,(id,t,body) in enumerate(sections,1))
page+=f'<noscript><div class="note">交互需要 JavaScript；正文、静态图和源码摘录仍可阅读。</div></noscript><footer class="lesson-footer">非官方学习材料 · 源码 {SHA} · <a href="../../THIRD_PARTY_NOTICES.md">引用与许可</a></footer></main></body></html>'
(D/'index.html').write_text(apply_entry(page,'06'))
m={'version':'0.2.1-alpha.1','commit':SHA,'checked':'2026-10-10','sources':sources,'excerpts':excerpts}
(D/'sources.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');(D/'sources.js').write_text('window.LESSON_SOURCES = '+json.dumps(m,ensure_ascii=False)+';\n')
print('Generated lesson 06:',len(sections),'sections,',len(excerpts),'exact excerpts.')
